#! /bin/sh

##################
#   startup
##################
wmname LG3D
startup() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
startup xrdb $HOME/.Xresources
startup $HOME/.config/polybar/launch.sh 
startup nitrogen --restore 
startup picom -f 
startup sxhkd 


bspc monitor -d I II III IV V VI VII VIII #IX X
bspc config border_width         2
bspc config window_gap           12
out = 2
bspc config bottom_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out))

bspc config split_ratio          0.50
bspc config focus_follows_pointer true

# rules
bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^3'
bspc rule -a yesplaymusic desktop='^6'
bspc rule -a icalingua desktop='^8'

bspc config normal_border_color "$inactive"
bspc config focused_border_color "$inactive"
# bspc config focused_border_color "$inactive"
bspc config presel_feedback_color "$inactive"


